## Author: Tito Valentin
## Name of Program: piSysStatus Gitleaks Configuration
## Date Created: 2026-07-13
## Description: Extends the default Gitleaks rules for repository history scans.
title = "piSysStatus gitleaks configuration"

[extend]
useDefault = true
